const resumeData = [
  {
    id: "nu",
    tag: "education",
    title: "northwestern university — b.s./m.s. computer science",
    shortTitle: "b.s./m.s. computer science",
    org: "northwestern",
    period: "2023 – 2027",
    year: "2023",
    sort: 2023,
    body: "b.s./m.s. in computer science with an ai concentration. relevant coursework: data structures & algorithms, artificial intelligence, scalable software architecture.",
    metric: "",
    stack: ["python", "algorithms", "ai"],
    facets: ["ai"],
    timeline: false,
    keywords: [
      "northwestern", "university", "computer science", "cs", "ai", "artificial intelligence",
      "machine learning", "ml", "data structures", "algorithms", "scalable software",
      "architecture", "undergraduate", "graduate", "evanston", "nu", "bs", "ms", "2027",
      "education", "degree", "concentration",
    ],
  },

  {
    id: "verkada",
    tag: "experience",
    title: "software engineer intern — verkada",
    shortTitle: "swe intern",
    org: "verkada",
    period: "present",
    year: "2026",
    sort: 2026.9,
    body: "software engineer intern on the business systems engineering team.",
    metric: "business systems engineering",
    stack: [],
    facets: ["infra"],
    timeline: true,
    keywords: [
      "verkada", "software engineering", "swe", "intern", "internship",
      "business systems", "business systems engineering", "physical security", "cloud",
    ],
  },
  {
    id: "salesforce",
    tag: "experience",
    title: "software engineer intern — salesforce",
    shortTitle: "swe intern",
    org: "salesforce",
    period: "jun 2026",
    year: "2026",
    sort: 2026.8,
    body: "software engineer intern on the availability & infrastructure team.",
    metric: "availability & infrastructure",
    stack: ["infrastructure", "availability"],
    facets: ["infra"],
    timeline: true,
    keywords: [
      "salesforce", "software engineering", "swe", "intern", "internship",
      "infrastructure", "availability", "enterprise", "crm", "cloud",
    ],
  },
  {
    id: "givelify",
    tag: "experience",
    title: "software engineer intern — givelify",
    shortTitle: "swe intern",
    org: "givelify",
    period: "sep – dec 2025",
    year: "2025",
    sort: 2025.9,
    body: "shipped a javascript log-tracking feature to 75,000 users, improving donation tracking in an agile environment. migrated web services from aws to kubernetes, improving scalability and deployment automation. wrote rest api contracts for backend services, improving onboarding across a 200+ engineer codebase.",
    metric: "75k users · aws → k8s",
    stack: ["javascript", "kubernetes", "aws", "rest"],
    facets: ["infra"],
    timeline: true,
    keywords: [
      "givelify", "javascript", "js", "log tracking", "donation", "agile", "aws",
      "kubernetes", "k8s", "migration", "rest", "api", "backend", "scalability",
      "deployment", "automation", "nonprofit", "fintech", "onboarding", "swe", "intern",
    ],
  },
  {
    id: "dimensional",
    tag: "experience",
    title: "software engineer intern — dimensional",
    shortTitle: "swe intern",
    org: "dimensional",
    period: "jun – aug 2025",
    year: "2025",
    sort: 2025.6,
    body: "engineered a python rest api and typescript dashboard surfacing real-time market metrics for 500+ employees. automated data processing in python for reporting, reducing analytics team workload by 6 hours per week. analyzed 1m+ records using sql and built visualizations in tableau to highlight behavioral trends.",
    metric: "1m records · 6h/week saved",
    stack: ["python", "typescript", "sql", "rest"],
    facets: ["infra", "full-stack"],
    timeline: true,
    keywords: [
      "dimensional", "python", "rest", "api", "typescript", "ts", "dashboard",
      "real-time", "market", "metrics", "finance", "fintech", "automation",
      "data processing", "reporting", "sql", "tableau", "visualization", "analytics",
      "swe", "intern",
    ],
  },
  {
    id: "ta",
    tag: "experience",
    title: "undergraduate teaching assistant — northwestern",
    shortTitle: "ta",
    org: "northwestern",
    period: "sep 2024 – jun 2025",
    year: "2024",
    sort: 2024.9,
    body: "led weekly sections covering graph algorithms, search techniques, and complexity analysis for 300+ students. evaluated programming assignments in python, providing structured feedback on algorithm correctness.",
    metric: "300+ students",
    stack: ["python", "algorithms"],
    facets: ["ai"],
    timeline: true,
    keywords: [
      "ta", "teaching assistant", "northwestern", "data structures", "algorithms",
      "graph", "search", "complexity", "python", "education", "teaching", "students",
      "feedback", "programming",
    ],
  },

  {
    id: "clinic",
    tag: "project",
    title: "mobile medical clinic optimization platform",
    shortTitle: "clinic optimization",
    org: "typescript · aws",
    period: "2025",
    year: "2025",
    sort: 2025.4,
    body: "created a typescript platform to identify underserved regions using public health and demographic data. developed a serverless backend with aws lambda and api gateway to generate optimized clinic routes.",
    metric: "serverless clinic routing",
    stack: ["typescript", "aws lambda", "api gateway"],
    facets: ["infra"],
    timeline: true,
    featured: true,
    diagram: ["health data", "lambda", "api gateway", "routes"],
    keywords: [
      "typescript", "ts", "healthcare", "health", "medical", "clinic", "optimization",
      "aws", "lambda", "serverless", "api gateway", "routes", "public health",
      "demographic", "data", "platform",
    ],
  },
  {
    id: "campus-events",
    tag: "project",
    title: "campus events platform",
    shortTitle: "campus events",
    org: "react · node.js",
    period: "2026",
    year: "2026",
    sort: 2026.2,
    body: "built a full-stack app using react and node.js serving 200+ students with interactive maps and event filtering. prototyped ui in figma, iterating on user flows and responsive layouts. won user design award for intuitive front-end.",
    metric: "200+ students · design award",
    stack: ["react", "node.js", "figma"],
    facets: ["full-stack"],
    timeline: true,
    keywords: [
      "react", "node", "node.js", "full stack", "fullstack", "javascript", "js",
      "figma", "ui", "ux", "design", "maps", "responsive", "award", "user design",
      "students", "events", "frontend", "backend",
    ],
  },
  {
    id: "nasa",
    tag: "project",
    title: "nasa space apps — data aggregation platform",
    shortTitle: "nasa space apps",
    org: "react · flask · rag",
    period: "2025",
    year: "2025",
    sort: 2025.3,
    body: "delivered a research aggregation platform using react and flask as part of the invite-only nasa space apps challenge. constructed an llm retrieval pipeline over 100+ scientific resources using vector embeddings for semantic search. implemented an ai research assistant using llms with rag to summarize papers and answer domain-specific queries.",
    metric: "100+ sources · rag pipeline",
    stack: ["react", "flask", "rag", "python"],
    facets: ["ai", "full-stack"],
    timeline: true,
    keywords: [
      "nasa", "space apps", "react", "flask", "python", "llm", "large language model",
      "ai", "rag", "retrieval augmented generation", "vector embeddings", "semantic search",
      "research", "hackathon", "machine learning", "ml", "nlp", "papers", "science",
    ],
  },

  {
    id: "colorstack",
    tag: "leadership",
    title: "colorstack — secretary",
    shortTitle: "secretary",
    org: "colorstack",
    period: "sep 2024 – present",
    year: "2024",
    sort: 2024.8,
    body: "organized meetings and maintained communication for 180+ student members in a tech diversity organization. directed workshop planning and coordinated technical skill-building sessions.",
    metric: "180+ members",
    stack: [],
    facets: ["leadership"],
    timeline: true,
    keywords: [
      "colorstack", "secretary", "diversity", "dei", "inclusion", "tech", "organization",
      "community", "workshops", "leadership", "students", "communication",
    ],
  },
  {
    id: "wildhacks",
    tag: "leadership",
    title: "wildhacks — corporate engagement",
    shortTitle: "corporate engagement",
    org: "wildhacks",
    period: "sep 2024 – present",
    year: "2024",
    sort: 2024.7,
    body: "coordinated partnerships with google, hudson river trading, and imc to sponsor northwestern's hackathon. supported a record 550 participants from 57 universities by organizing recruiting sessions and technical workshops.",
    metric: "550 participants · 57 universities",
    stack: [],
    facets: ["leadership"],
    timeline: true,
    keywords: [
      "wildhacks", "hackathon", "corporate", "engagement", "sponsorship", "google",
      "hudson river trading", "hrt", "imc", "partnerships", "recruiting", "workshops",
      "leadership", "universities", "northwestern",
    ],
  },
  {
    id: "raiso",
    tag: "leadership",
    title: "raiso — web dev committee",
    shortTitle: "web dev committee",
    org: "raiso",
    period: "",
    year: "2024",
    sort: 2024.5,
    body: "web development committee member at raiso (responsible ai student organization) at northwestern.",
    metric: "responsible ai",
    stack: ["web"],
    facets: ["leadership", "ai", "full-stack"],
    timeline: true,
    keywords: [
      "raiso", "responsible ai", "web dev", "web development", "frontend",
      "committee", "ai", "organization", "northwestern",
    ],
  },

  {
    id: "languages",
    tag: "skills",
    title: "languages",
    shortTitle: "languages",
    org: "",
    period: "",
    year: "",
    sort: 0,
    body: "python, typescript, sql, c++, java, javascript.",
    metric: "",
    stack: ["python", "typescript", "sql", "c++", "java", "javascript"],
    facets: [],
    timeline: false,
    keywords: [
      "python", "typescript", "ts", "sql", "c++", "cpp", "java", "javascript", "js",
      "language", "programming", "coding",
    ],
  },
  {
    id: "systems",
    tag: "skills",
    title: "systems & tools",
    shortTitle: "systems & tools",
    org: "",
    period: "",
    year: "",
    sort: 0,
    body: "git, docker, kubernetes, linux, google cloud platform, vs code, intellij, eclipse, redis.",
    metric: "",
    stack: ["git", "docker", "kubernetes", "linux", "gcp", "redis"],
    facets: ["infra"],
    timeline: false,
    keywords: [
      "git", "docker", "kubernetes", "k8s", "linux", "gcp", "google cloud", "vs code",
      "vscode", "intellij", "eclipse", "redis", "tools", "devops", "cloud", "infrastructure",
    ],
  },
];
